### ISSUE TITLE
No need to URLEncode

### ISSUE THREAD

**Issue by Dan-Price-Intrepid** [amcdonald0214/ParseHub-CSharp#1]
Great code - thanks for posting it!

Just one bit of feedback: my experience was that the start URL (and possibly the start template) does not need the URL Encoding statement HttpUtility.UrlEncode in RunProject.  My attempts to set start URL didn't work until I removed the URL encoding.

Cheers,
Dan

**Comment by amcdonald0214** [comment]
Hi Dan,

Thanks for the note and the feedback on the UrlEncoding. I will look at that and update the code accordingly.

Best,
Aaron

**Comment by amcdonald0214** [comment]
Fixed issue with code update
